### ISSUE TITLE
Inverted keyboard arrows accessibility

### ISSUE THREAD

**Issue by dandv** [geminilabs/star-rating.js#1]
Same issue as in [this other star rating component](https://github.com/LunarLogic/starability/issues/15): pressing the left arrow while the rating has focus increases the rating, while pressing the right arrow decreases it.

**Comment by pryley** [comment]
@dandv The `star-rating.js` plugin transforms a `<select>` element into stars. The reason the left/right arrows move the wrong way is because the `<option>` elements are ordered DESC instead of ASC. You can always change the order to ASC and the arrow keys will work correctly.

```html
<!-- options are sorted in DESC order -->
<select id="star-rating-1">
	<option value="">Select a rating</option>
	<option value="5">5</option>
	<option value="4">4</option>
	<option value="3">3</option>
	<option value="2">2</option>
	<option value="1">1</option>
</select>

<!-- options are sorted in ASC order -->
<select id="star-rating-1">
	<option value="">Select a rating</option>
	<option value="1">1</option>
	<option value="2">2</option>
	<option value="3">3</option>
	<option value="4">4</option>
	<option value="5">5</option>
</select>
```

Order really only matters when JS is disabled and you want the fallback to encourage the higher rating option (hence, DESC order).

Would you still consider this an issue?
