### ISSUE TITLE
Some bugs and ideas

### ISSUE THREAD

**Issue by Sir-Genius** [geminilabs/star-rating.js#12]
Hi, Paul! First of all thanks for this awesome plugin. You did a great job! Now about the issues.
1. Despite your fix in v3.4.0 there are still warnings in DevTools related to non-passive event listeners. I use latest Google Chrome (v89.0.4389.82) and Star-rating.js v4.1.1.
2. Right-clicking on a rating triggers the select event. This is very annoying.
3. It would be nice to implement fractional rating (with `initialRating` option). Now I do this way (maybe it will come in handy): [codepen](https://codepen.io/Sirgenius/pen/oNYapQj).

Sorry for my English. I would be grateful for your response!

**Comment by pryley** [comment]
1. I have added `{passive:false}` to the touch events but since these are touch events, that verbose notice will be shown in Chrome regardless. https://github.com/pryley/star-rating.js/blob/62873ee2a36d039c41d3a81b21adfcc4d21ad882/src/widget.js#L117-L119
2. I can add a check for right-click
3. How is this useful? Star Rating does not support fractional ratings on purpose as it is meant to be used in a form, not to display a rating.

**Comment by fammifarendra** [comment]
It is useful, 
Sometimes we need to change our rating, and we want to know what is our rating before
But this can be done by setting selected one of the option

**Comment by Sir-Genius** [comment]
Found another issue: the selection with a mouse doesn't work if `select` has focus.

**Comment by pryley** [comment]
> Found another issue: the selection with a mouse doesn't work if `select` has focus.

Fixed in v4.1.3

For the right-click check, feel free to add a pull-request.
