### ISSUE TITLE
Make it possible to disable voting

### ISSUE THREAD

**Issue by jenstornell** [geminilabs/star-rating.js#6]
Sometimes it make sense to only show the rating, for example in an archive with many items. Maybe it would be good to also be able to disable voting?

**Comment by pryley** [comment]
The star-rating.js library transforms a [select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) dropdown (usually found in a form which submits data) to a star rating widget.

When would you have select elements in an archive list? It seems to me that in this case, you would be displaying the saved rating value rather than a dropdown.

**Comment by jenstornell** [comment]
Fair point.

**Comment by pryley** [comment]
Here is an example of how you would construct a read-only (5 stars) star-rating (assuming PHP):

```html
<span class="gl-star-rating-stars s<?= intval( $rating ) * 10; ?>">
    <?= str_repeat( '<span></span>', 5 ); ?>
</span>
```
